### PR TITLE
Add a MANIFEST.in to package locale po

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
Refs #96, do you mind testing that out @andresmrm, please ?

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
``python -m build``:
```
...
creating build/bdist.linux-x86_64/wheel/django_zxcvbn_password_validator/locale
creating build/bdist.linux-x86_64/wheel/django_zxcvbn_password_validator/locale/nl
creating build/bdist.linux-x86_64/wheel/django_zxcvbn_password_validator/locale/nl/LC_MESSAGES
copying build/lib/django_zxcvbn_password_validator/locale/nl/LC_MESSAGES/django.po -> build/bdist.linux-x86_64/wheel/django_zxcvbn_password_validator/locale/nl/LC_MESSAGES
creating build/bdist.linux-x86_64/wheel/django_zxcvbn_password_validator/locale/pt_BR
creating build/bdist.linux-x86_64/wheel/django_zxcvbn_password_validator/locale/pt_BR/LC_MESSAGES
copying build/lib/django_zxcvbn_password_validator/locale/pt_BR/LC_MESSAGES/django.po -> build/bdist.linux-x86_64/wheel/django_zxcvbn_password_validator/locale/pt_BR/LC_MESSAGES
creating build/bdist.linux-x86_64/wheel/django_zxcvbn_password_validator/locale/fr
creating build/bdist.linux-x86_64/wheel/django_zxcvbn_password_validator/locale/fr/LC_MESSAGES
copying build/lib/django_zxcvbn_password_validator/locale/fr/LC_MESSAGES/django.po -> build/bdist.linux-x86_64/wheel/django_zxcvbn_password_validator/locale/fr/LC_MESSAGES
...
```
So I'm hopeful it works.

**Comment by andresmrm** [comment]
It didn't work packing only the .po files. But it did after also including the .mo files.
Replacing the first line to this worked for me: `recursive-include django_zxcvbn_password_validator/locale`

**Comment by Pierre-Sassoulas** [comment]
I'm not well versed in django's best practices, are the lib supposed to compile the messages themselves ? (or should the user do a compile messages ?). I guess if it's cross platform including the mo is fine.

**Comment by andresmrm** [comment]
I'm also not sure... But a `ls **/*.mo` at my Python env folder finds a lot of stuff for many Django third party apps, even for Django itself...

**Comment by Pierre-Sassoulas** [comment]
Thank you for the state of the art 😄 Let's include mo then.

**Pull request merged**
