### PR TITLE
Use new zxcvbn package name

### LINKED ISSUE #2: zxcvbn-python has been renamed to zxcvbn
This package now ends up with a deprecation warning from zxcvbn-python, because they've opted to change to the `zxcvbn` package name instead.

### PR DESCRIPTION
**Pull request by ryanhiebert**
Fixes #2

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Thank you for the merge request :)

**Comment by ryanhiebert** [comment]
cool. I'm in no particular rush, but when are you thinking you'll likely be able to cut a new release?

**Comment by Pierre-Sassoulas** [comment]
I just released [1.2.5](https://pypi.org/project/django-zxcvbn-password-validator/), let me know if it works for you.

**Comment by ryanhiebert** [comment]
works for me, sorry for the delay in reporting back. Thank you!

**Pull request merged**
